// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7UMzO6JLFVXkY2Voo-EzovoxcgHHqvv0',
    appId: '1:602698384232:web:371b371b236b145e0f0cdd',
    messagingSenderId: '602698384232',
    projectId: 'wedscore-3c2fc',
    authDomain: 'wedscore-3c2fc.firebaseapp.com',
    storageBucket: 'wedscore-3c2fc.firebasestorage.app',
    measurementId: 'G-54CPQPL3J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzF-1EgQ5zov_BvIuIkeocTFmDMSN0SVY',
    appId: '1:602698384232:android:0834d457f5df6ed00f0cdd',
    messagingSenderId: '602698384232',
    projectId: 'wedscore-3c2fc',
    storageBucket: 'wedscore-3c2fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3sT-0lIXT6LS8--dCeUB-0XZ_t-TfdTM',
    appId: '1:602698384232:ios:5354e61770519c830f0cdd',
    messagingSenderId: '602698384232',
    projectId: 'wedscore-3c2fc',
    storageBucket: 'wedscore-3c2fc.firebasestorage.app',
    iosClientId: '602698384232-hgkq9fd48r95rv0p5a702g0k3ohsa6ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedscore',
  );

}